// src/lib/webhook.ts
// GitHub Webhook listener — Autonomous Git-to-CMS Observer.
// Starts an HTTP server that receives GitHub push events,
// auto-drafts a CMS project entry, and notifies the user via stderr.

import { createServer, IncomingMessage, ServerResponse } from "node:http";
import { createHmac } from "node:crypto";
import type { Config } from "./config.js";
import type { AuditLogger } from "./audit.js";
import { ApiClient } from "./api-client.js";

// ─── Types ────────────────────────────────────────────────────────────────────

interface GitHubPushPayload {
  ref: string;
  repository: {
    full_name: string;
    name: string;
    html_url: string;
    homepage: string | null;
    description: string | null;
    language: string | null;
    topics: string[];
    default_branch: string;
  };
  head_commit: {
    id: string;
    message: string;
    timestamp: string;
    author: { name: string; email: string };
    added: string[];
    modified: string[];
    removed: string[];
  } | null;
  pusher: { name: string };
  commits: Array<{
    message: string;
    timestamp: string;
    author: { name: string };
  }>;
}

export interface WebhookEvent {
  type: string;
  repo: string;
  branch: string;
  commitMessage: string;
  pusher: string;
  timestamp: string;
  filesChanged: string[];
}

// ─── HMAC Verification ────────────────────────────────────────────────────────

function verifySignature(body: Buffer, signature: string, secret: string): boolean {
  const expected = `sha256=${createHmac("sha256", secret).update(body).digest("hex")}`;
  // Constant-time comparison prevents timing attacks
  if (expected.length !== signature.length) return false;
  let result = 0;
  for (let i = 0; i < expected.length; i++) {
    result |= expected.charCodeAt(i) ^ signature.charCodeAt(i);
  }
  return result === 0;
}

// ─── Shadow Draft Creator ─────────────────────────────────────────────────────

async function createShadowDraft(
  config: Config,
  payload: GitHubPushPayload,
): Promise<{ id?: string; title: string } | null> {
  if (!config.endpoints.projects) return null;

  const repo = payload.repository;
  const client = new ApiClient(config);

  const slug = repo.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const title = repo.name;
  const commitMessages = payload.commits
    .slice(0, 5)
    .map((c) => `- ${c.message.split("\n")[0]}`)
    .join("\n");

  const projectData = {
    title,
    slug,
    summary: repo.description ?? `${title} — updated via GitHub push`,
    description: [
      `## ${title}`,
      ``,
      repo.description ?? "",
      ``,
      `### Recent Changes`,
      commitMessages,
      ``,
      `*Shadow draft auto-generated by cms-mcp webhook on ${new Date().toISOString().slice(0, 10)}*`,
    ].join("\n").trim(),
    repo_url: repo.html_url,
    live_url: repo.homepage ?? undefined,
    tags: repo.topics ?? [],
    status: "draft",
    _shadow: true,
    _webhook_generated: true,
  };

  try {
    const result = await client.post<Record<string, unknown>>(
      config.endpoints.projects,
      projectData,
    );
    return { id: String(result["id"] ?? ""), title };
  } catch {
    return null;
  }
}

// ─── Notification formatter ───────────────────────────────────────────────────

function formatNotification(event: WebhookEvent, draftId?: string): string {
  const lines = [
    ``,
    `╔══════════════════════════════════════════════╗`,
    `║  cms-mcp: GitHub Push Detected               ║`,
    `╚══════════════════════════════════════════════╝`,
    ``,
    `  Repo:    ${event.repo}`,
    `  Branch:  ${event.branch}`,
    `  By:      ${event.pusher}`,
    `  Commit:  ${event.commitMessage.slice(0, 60)}`,
    ``,
    draftId
      ? `  ✅ Shadow draft created (ID: ${draftId})`
      : `  ℹ️  No projects endpoint configured — no draft created`,
    ``,
    `  → Ask Claude: "I see you pushed to ${event.repo}. Want to update the portfolio entry?"`,
    ``,
  ];
  return lines.join("\n");
}

// ─── Request body reader ──────────────────────────────────────────────────────

function readBody(req: IncomingMessage): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let size = 0;
    req.on("data", (chunk: Buffer) => {
      size += chunk.length;
      if (size > 5 * 1024 * 1024) {
        reject(new Error("Payload too large"));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

// ─── HTTP Request Handler ─────────────────────────────────────────────────────

function createHandler(
  config: Config,
  audit: AuditLogger,
  webhookPath: string,
  secret: string,
) {
  return async (req: IncomingMessage, res: ServerResponse) => {
    // Health check
    if (req.method === "GET" && req.url === "/health") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ status: "ok", server: "cms-mcp-webhook" }));
      return;
    }

    // Webhook endpoint
    if (req.method !== "POST" || req.url !== webhookPath) {
      res.writeHead(404);
      res.end("Not found");
      return;
    }

    const event = req.headers["x-github-event"] as string;
    const signature = req.headers["x-hub-signature-256"] as string;

    if (!signature) {
      res.writeHead(401);
      res.end("Missing signature");
      return;
    }

    let body: Buffer;
    try {
      body = await readBody(req);
    } catch {
      res.writeHead(413);
      res.end("Payload too large");
      return;
    }

    // Verify HMAC signature
    if (!verifySignature(body, signature, secret)) {
      res.writeHead(401);
      res.end("Invalid signature");
      audit.log({
        timestamp: new Date().toISOString(),
        tool: "webhook",
        args: { event, source: "github" },
        outcome: "error",
        error: "Invalid webhook signature",
      });
      return;
    }

    // Acknowledge immediately — GitHub expects a fast response
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ received: true }));

    // Process asynchronously
    if (event !== "push") {
      process.stderr.write(`[webhook] Ignored non-push event: ${event}\n`);
      return;
    }

    let payload: GitHubPushPayload;
    try {
      payload = JSON.parse(body.toString("utf-8"));
    } catch {
      process.stderr.write("[webhook] Failed to parse payload JSON\n");
      return;
    }

    const branch = payload.ref?.replace("refs/heads/", "") ?? "unknown";
    const commitMsg = payload.head_commit?.message?.split("\n")[0] ?? "(no commit message)";
    const filesChanged = [
      ...(payload.head_commit?.added ?? []),
      ...(payload.head_commit?.modified ?? []),
    ].slice(0, 20);

    const webhookEvent: WebhookEvent = {
      type: "push",
      repo: payload.repository.full_name,
      branch,
      commitMessage: commitMsg,
      pusher: payload.pusher.name,
      timestamp: payload.head_commit?.timestamp ?? new Date().toISOString(),
      filesChanged,
    };

    // Only create shadow drafts for pushes to the default branch
    let draftResult: { id?: string; title: string } | null = null;
    if (branch === payload.repository.default_branch && !config.readOnly) {
      draftResult = await createShadowDraft(config, payload);
    }

    // Notify via stderr — Claude Desktop surfaces this in the sidebar
    process.stderr.write(formatNotification(webhookEvent, draftResult?.id));

    audit.log({
      timestamp: new Date().toISOString(),
      tool: "webhook",
      args: { event: "push", repo: webhookEvent.repo, branch },
      outcome: "success",
    });
  };
}

// ─── Start Server ─────────────────────────────────────────────────────────────

export function startWebhookServer(
  config: Config,
  audit: AuditLogger,
): { port: number; close: () => Promise<void> } {
  const webhookConf = config.webhook!;
  const secret = webhookConf.secret;
  const port = webhookConf.port;
  const path = webhookConf.path ?? "/webhook";

  const server = createServer(createHandler(config, audit, path, secret));

  server.listen(port, () => {
    process.stderr.write(`[cms-mcp] Webhook listener: http://localhost:${port}${path}\n`);
    process.stderr.write(`[cms-mcp] GitHub → Settings → Webhooks → Add webhook\n`);
    process.stderr.write(`[cms-mcp]   Payload URL: http://YOUR_PUBLIC_IP:${port}${path}\n`);
    process.stderr.write(`[cms-mcp]   Content type: application/json\n`);
    process.stderr.write(`[cms-mcp]   Events: Pushes\n`);
  });

  const close = () =>
    new Promise<void>((resolve, reject) => {
      server.close((err) => (err ? reject(err) : resolve()));
    });

  return { port, close };
}
